export const computingTopics = [
  'algorithm',
  'artificial intelligence',
  'big data',
  'blockchain',
  'cloud computing',
  'computer graphics',
  'computer network',
  'computer programming',
  'computer vision',
  'cybersecurity',
  'data mining',
  'database',
  'deep learning',
  'digital signal processing',
  'distributed systems',
  'e-commerce',
  'encryption',
  'ethics',
  'game development',
  'genetic algorithm',
  'graph theory',
  'human-computer interaction',
  'information retrieval',
  'internet of things',
  'machine learning',
  'natural language processing',
  'neural networks',
  'operating system',
  'parallel computing',
  'pattern recognition',
  'programming languages',
  'quantum computing',
  'robotics',
  'search engine',
  'security',
  'semantic web',
  'simulation',
  'software engineering',
  'speech recognition',
  'virtual reality',
  'web development',
  '3D printing',
  'agile methodology',
  'android development',
  'API',
  'augmented reality',
  'back-end development',
  'bioinformatics',
  'business intelligence',
  'chatbot',
  'cloud storage',
  'CMS',
  'computer hardware',
  'content management',
  'data analytics',
  'data science',
  'data visualization',
  'desktop application',
  'DevOps',
  'digital marketing',
  'e-learning',
  'front-end development',
  'game engine',
  'geographic information system',
  'git',
  'iOS development',
  'Java',
  'JavaScript',
  'jQuery',
  'Linux',
  'machine vision',
  'MATLAB',
  'microservices',
  'mobile application',
  'natural language generation',
  'natural language understanding',
  'node.js',
  'NoSQL',
  'object-oriented programming',
  'OpenGL',
  'PHP',
  'Python',
  'React',
  'RESTful',
  'Ruby',
  'Scala',
  'serverless computing',
  'shell scripting',
  'social media',
  'software testing',
  'SQL',
  'Swift',
  'test-driven development',
  'UI/UX design',
  'virtual assistant',
  'web application',
  'web scraping',
  'Windows',
  'WordPress',
];
